import { useLocation, useNavigate } from "react-router-dom";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { useState } from "react";
import axios from "axios";
import {
  FileSpreadsheet,
  FileText,
  ChevronDown,
  ChevronUp,
  CheckCircle2,
  XCircle,
  ArrowLeft,
  AlertTriangle,
  RefreshCw,
  ShieldCheck,
  ShieldX,
  RotateCcw,
  Loader2,
  ScanSearch,
} from "lucide-react";

// ─── Types ────────────────────────────────────────────────────────────────────

interface Detection {
  class_name: string;
  confidence: number;
  bbox: [number, number, number, number];
  // NOTE: 'accepted' field is intentionally removed.
  // Every detection returned by the model is a real defect.
  // One defect = blade is DEFECTIVE. No threshold. No accepted/rejected.
}

interface BatchResult {
  filename?: string;
  predicted_image?: string;
  detections?: Detection[];
  error?: string;
  blade_defective?: boolean;           // true = defective, false = clear
  body_message?: string | null;        // set when body isolation failed
}

type BladeLabel = "approved" | "defective" | "retrain" | null;

// ─── PDF Generation ───────────────────────────────────────────────────────────

const generatePDF = (
  batchResults: BatchResult[],
  labels: Record<number, BladeLabel>
) => {
  const doc   = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 15;

  const addHeader = () => {
    doc.setFillColor(15, 23, 42);
    doc.rect(0, 0, pageW, 22, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(255, 255, 255);
    doc.text("BLADE DEFECT INSPECTION REPORT", margin, 14);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(
      `Page ${doc.getNumberOfPages()}   |   ${new Date().toLocaleString()}`,
      pageW - margin, 14, { align: "right" }
    );
  };

  const addFooter = () => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(180, 180, 180);
    doc.text("Generated by Blade Inspection System", margin, pageH - 6);
    doc.text("CONFIDENTIAL", pageW - margin, pageH - 6, { align: "right" });
  };

  addHeader();
  let y = 34;

  // ── Summary heading ──
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(15, 23, 42);
  doc.text("Inspection Summary", margin, y);
  y += 8;
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.3);
  doc.line(margin, y, pageW - margin, y);
  y += 8;

  const totalImages     = batchResults.length;
  const defectiveImages = batchResults.filter((r) => r.blade_defective).length;
  const clearImages     = batchResults.filter((r) => !r.blade_defective && !r.error && !r.body_message).length;
  const noBodyImages    = batchResults.filter((r) => r.body_message && !r.error).length;
  const failedImages    = batchResults.filter((r) => r.error).length;
  const totalDefects    = batchResults.reduce((s, r) => s + (r.detections?.length || 0), 0);
  const approvedBlades  = Object.values(labels).filter((l) => l === "approved").length;
  const defectiveBlades = Object.values(labels).filter((l) => l === "defective").length;
  const retrainBlades   = Object.values(labels).filter((l) => l === "retrain").length;

  const stats: { label: string; value: string; color: [number, number, number] }[] = [
    { label: "Total Images",     value: String(totalImages),     color: [30,  64, 175] },
    { label: "CLEAR",            value: String(clearImages),     color: [21, 128,  61] },
    { label: "DEFECTIVE",        value: String(defectiveImages), color: [185, 28,  28] },
    { label: "No Body Found",    value: String(noBodyImages),    color: [180, 83,   9] },
    { label: "Failed",           value: String(failedImages),    color: [100, 116, 139] },
    { label: "Total Defects",    value: String(totalDefects),    color: [30,  64, 175] },
    { label: "Operator: OK",     value: String(approvedBlades),  color: [21, 128,  61] },
    { label: "Operator: Bad",    value: String(defectiveBlades), color: [185, 28,  28] },
    { label: "Retrain Flagged",  value: String(retrainBlades),   color: [109, 40, 217] },
  ];

  const boxW = (pageW - margin * 2 - 4 * (stats.length - 1)) / stats.length;
  stats.forEach((s, i) => {
    const bx = margin + i * (boxW + 4);
    doc.setFillColor(248, 250, 252);
    doc.setDrawColor(226, 232, 240);
    doc.roundedRect(bx, y, boxW, 20, 2, 2, "FD");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(...s.color);
    doc.text(s.value, bx + boxW / 2, y + 11, { align: "center" });
    doc.setFont("helvetica", "normal");
    doc.setFontSize(6);
    doc.setTextColor(100, 116, 139);
    doc.text(s.label, bx + boxW / 2, y + 17, { align: "center" });
  });

  y += 30;

  // ── Per-image sections ──
  batchResults.forEach((result, index) => {
    const name       = result.filename || `Image ${index + 1}`;
    const bladeLabel = labels[index];

    if (y > pageH - 100) {
      addFooter();
      doc.addPage();
      y = 30;
      addHeader();
    }

    doc.setFillColor(241, 245, 249);
    doc.setDrawColor(226, 232, 240);
    doc.roundedRect(margin, y, pageW - margin * 2, 10, 2, 2, "FD");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(15, 23, 42);
    doc.text(`${index + 1}. ${name}`, margin + 4, y + 6.5);

    // Automated verdict
    if (!result.error && !result.body_message) {
      const verdictColor: [number, number, number] = result.blade_defective
        ? [185, 28, 28]
        : [21, 128, 61];
      const verdictText = result.blade_defective ? "DEFECTIVE" : "CLEAR";
      doc.setFont("helvetica", "bold");
      doc.setFontSize(8);
      doc.setTextColor(...verdictColor);
      doc.text(verdictText, pageW - margin - 40, y + 6.5, { align: "right" });
    }

    // Operator label
    if (bladeLabel) {
      const lColor: [number, number, number] =
        bladeLabel === "approved"  ? [21, 128,  61] :
        bladeLabel === "defective" ? [185, 28,  28] :
                                     [109, 40, 217];
      const lText =
        bladeLabel === "approved"  ? "✓ OPERATOR: OK"      :
        bladeLabel === "defective" ? "✗ OPERATOR: DEFECTIVE" :
                                     "↺ RETRAIN";
      doc.setFont("helvetica", "bold");
      doc.setFontSize(8);
      doc.setTextColor(...lColor);
      doc.text(lText, pageW - margin - 4, y + 6.5, { align: "right" });
    }

    y += 14;

    if (result.error) {
      doc.setFont("helvetica", "italic");
      doc.setFontSize(9);
      doc.setTextColor(185, 28, 28);
      doc.text(`Error: ${result.error}`, margin + 4, y);
      y += 12;
      return;
    }

    if (result.body_message) {
      doc.setFont("helvetica", "italic");
      doc.setFontSize(9);
      doc.setTextColor(180, 83, 9);
      doc.text(`⚠ ${result.body_message}`, margin + 4, y);
      y += 12;
      return;
    }

    const imgW = 70;
    const imgH = 55;

    if (result.predicted_image) {
      try {
        doc.addImage(
          `data:image/png;base64,${result.predicted_image}`,
          "PNG", margin, y, imgW, imgH
        );
      } catch {
        doc.setFillColor(241, 245, 249);
        doc.rect(margin, y, imgW, imgH, "F");
        doc.setFontSize(8);
        doc.setTextColor(148, 163, 184);
        doc.text("Image unavailable", margin + imgW / 2, y + imgH / 2, { align: "center" });
      }
    }

    const tableX = margin + imgW + 6;
    const tableW = pageW - margin - tableX;

    if (!result.detections || result.detections.length === 0) {
      doc.setFillColor(240, 253, 244);
      doc.setDrawColor(187, 247, 208);
      doc.roundedRect(tableX, y, tableW, 20, 2, 2, "FD");
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9);
      doc.setTextColor(21, 128, 61);
      doc.text("No defects detected — CLEAR", tableX + tableW / 2, y + 12, { align: "center" });
    } else {
      // Defect table — no ACCEPTED/REJECTED column
      autoTable(doc, {
        startY: y,
        margin: { left: tableX, right: margin },
        tableWidth: tableW,
        head: [["Defect Class", "Confidence", "BBox (x,y,w,h)"]],
        body: result.detections.map((d) => [
          d.class_name,
          `${(d.confidence * 100).toFixed(1)}%`,
          d.bbox.join(", "),
        ]),
        styles: { fontSize: 7.5, cellPadding: 2.5, lineColor: [226, 232, 240], lineWidth: 0.2 },
        headStyles: { fillColor: [185, 28, 28], textColor: [255, 255, 255], fontStyle: "bold", fontSize: 7.5 },
        bodyStyles: { textColor: [30, 41, 59] },
        columnStyles: {
          0: { cellWidth: "auto" },
          1: { cellWidth: 18, halign: "center" },
          2: { cellWidth: "auto", halign: "center" },
        },
      });

      // Blade verdict box below table
      const tableBottom = (doc as any).lastAutoTable?.finalY ?? y + 20;
      doc.setFillColor(255, 235, 235);
      doc.setDrawColor(248, 113, 113);
      doc.roundedRect(tableX, tableBottom + 2, tableW, 10, 2, 2, "FD");
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9);
      doc.setTextColor(185, 28, 28);
      doc.text(
        `BLADE DEFECTIVE — ${result.detections.length} defect${result.detections.length !== 1 ? "s" : ""} detected`,
        tableX + tableW / 2, tableBottom + 8, { align: "center" }
      );
    }

    y = Math.max(y + imgH, (doc as any).lastAutoTable?.finalY ?? y) + 14;
  });

  addFooter();
  doc.save(`Blade_Inspection_Report_${new Date().toISOString().split("T")[0]}.pdf`);
};

// ─── Component ────────────────────────────────────────────────────────────────

const ResultsBatchPage = () => {
  const location    = useLocation();
  const navigate    = useNavigate();
  const batchResults: BatchResult[] = location.state?.batchResults || [];
  const excelReport: string | null  = location.state?.excelReport  || null;

  const [expandedIndex, setExpandedIndex] = useState<number | null>(0);
  const [labels,        setLabels]        = useState<Record<number, BladeLabel>>({});
  const [labelLoading,  setLabelLoading]  = useState<Record<number, boolean>>({});
  const [labelError,    setLabelError]    = useState<Record<number, string>>({});

  const handleLabel = async (
    index: number,
    result: BatchResult,
    label: BladeLabel
  ) => {
    if (!label) return;

    const isDeselect  = labels[index] === label;
    const newLabel: BladeLabel = isDeselect ? null : label;
    setLabels((prev) => ({ ...prev, [index]: newLabel }));
    if (isDeselect) return;

    setLabelLoading((prev) => ({ ...prev, [index]: true }));
    setLabelError((prev)   => ({ ...prev, [index]: "" }));

    try {
      await axios.post("http://localhost:5000/save-label", {
        filename:   result.filename || `image_${index}.png`,
        label:      newLabel,
        image_b64:  result.predicted_image || "",
        detections: result.detections || [],
      });
    } catch (e: any) {
      setLabels((prev) => ({ ...prev, [index]: null }));
      setLabelError((prev) => ({
        ...prev,
        [index]: e?.response?.data?.error || "Failed to save label.",
      }));
    } finally {
      setLabelLoading((prev) => ({ ...prev, [index]: false }));
    }
  };

  const downloadExcel = () => {
    if (!excelReport) return;
    window.open(`http://localhost:5000/download/${excelReport}`, "_blank");
  };

  // ── Summary counts ──
  const defectiveCount  = batchResults.filter((r) => r.blade_defective).length;
  const clearCount      = batchResults.filter((r) => !r.blade_defective && !r.error && !r.body_message).length;
  const noBodyCount     = batchResults.filter((r) => r.body_message && !r.error).length;
  const totalDefects    = batchResults.reduce((s, r) => s + (r.detections?.length || 0), 0);
  const approvedCount   = Object.values(labels).filter((l) => l === "approved").length;
  const opDefectCount   = Object.values(labels).filter((l) => l === "defective").length;
  const retrainCount    = Object.values(labels).filter((l) => l === "retrain").length;

  return (
    <div className="min-h-screen bg-slate-50" style={{ fontFamily: "'DM Sans', sans-serif" }}>
      <link
        href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@300;400;500;600;700&family=DM+Mono:wght@400;500&display=swap"
        rel="stylesheet"
      />

      {/* ── Top bar ── */}
      <div className="bg-slate-900 text-white px-8 py-4 flex items-center justify-between sticky top-0 z-20">
        <div className="flex items-center gap-4">
          <button
            onClick={() => navigate("/")}
            className="flex items-center gap-2 text-slate-400 hover:text-white transition-colors text-sm"
          >
            <ArrowLeft className="w-4 h-4" />
            New Inspection
          </button>
          <div className="w-px h-5 bg-slate-700" />
          <h1 className="font-semibold text-sm tracking-wide">Inspection Results</h1>
        </div>
        <div className="flex items-center gap-3">
          <button
            onClick={() => navigate("/retrain")}
            className="flex items-center gap-2 px-4 py-2 bg-indigo-600 hover:bg-indigo-700 rounded-lg text-xs font-semibold transition-colors"
          >
            <RefreshCw className="w-3.5 h-3.5" />
            Retrain Module
          </button>
          <span className="text-xs text-slate-400">
            {batchResults.length} image{batchResults.length !== 1 ? "s" : ""}
          </span>
        </div>
      </div>

      <div className="max-w-5xl mx-auto px-6 py-8 flex flex-col gap-6">

        {/* ── Summary cards ── */}
        <div className="grid grid-cols-3 sm:grid-cols-7 gap-3">
          {[
            { label: "Total Inspected",  value: batchResults.length, color: "text-slate-800",   bg: "bg-white",      border: "border-slate-200"   },
            { label: "CLEAR",            value: clearCount,           color: "text-emerald-700", bg: "bg-emerald-50", border: "border-emerald-200" },
            { label: "DEFECTIVE",        value: defectiveCount,       color: "text-red-700",     bg: "bg-red-50",     border: "border-red-200"     },
            { label: "No Body Found",    value: noBodyCount,          color: "text-amber-700",   bg: "bg-amber-50",   border: "border-amber-200"   },
            { label: "Total Defects",    value: totalDefects,         color: "text-blue-700",    bg: "bg-blue-50",    border: "border-blue-200"    },
            { label: "Operator Retrain", value: retrainCount,         color: "text-violet-700",  bg: "bg-violet-50",  border: "border-violet-200"  },
            { label: "Operator Labels",  value: approvedCount + opDefectCount + retrainCount, color: "text-slate-700", bg: "bg-slate-100", border: "border-slate-300" },
          ].map((card) => (
            <div key={card.label} className={`${card.bg} rounded-xl border ${card.border} px-4 py-3`}>
              <p className={`text-2xl font-bold ${card.color}`}>{card.value}</p>
              <p className="text-xs text-slate-500 mt-0.5 leading-tight">{card.label}</p>
            </div>
          ))}
        </div>

        {/* ── Logic explanation banner ── */}
        <div className="bg-slate-900 text-white rounded-xl px-5 py-4 flex flex-wrap gap-6 text-xs">
          <div className="flex items-start gap-2">
            <XCircle className="w-4 h-4 text-red-400 shrink-0 mt-0.5" />
            <div>
              <p className="font-semibold text-red-300">Any defect detected → DEFECTIVE</p>
              <p className="text-slate-400 mt-0.5">Even one detection fails the blade. All model detections are treated as real defects.</p>
            </div>
          </div>
          <div className="flex items-start gap-2">
            <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0 mt-0.5" />
            <div>
              <p className="font-semibold text-emerald-300">Zero detections → CLEAR</p>
              <p className="text-slate-400 mt-0.5">The blade passes automated inspection with no defects found.</p>
            </div>
          </div>
          <div className="flex items-start gap-2">
            <RotateCcw className="w-4 h-4 text-violet-400 shrink-0 mt-0.5" />
            <div>
              <p className="font-semibold text-violet-300">Model wrong? → Retrain</p>
              <p className="text-slate-400 mt-0.5">If the result is incorrect, flag it below — the image is queued to improve the model.</p>
            </div>
          </div>
        </div>

        {/* ── Operator label legend ── */}
        <div className="bg-white border border-slate-200 rounded-xl px-5 py-4 flex flex-wrap gap-5 text-xs text-slate-600">
          <p className="font-semibold text-slate-500 uppercase tracking-wide w-full">
            Operator Labels{" "}
            <span className="font-normal normal-case text-slate-400 ml-1">
              — optional; confirm or override the automated result
            </span>
          </p>
          <div className="flex items-start gap-2">
            <ShieldCheck className="w-4 h-4 text-emerald-600 shrink-0 mt-0.5" />
            <div>
              <p className="font-semibold text-emerald-700">Approved</p>
              <p className="text-slate-400">Operator confirms blade is good (model agreed).</p>
            </div>
          </div>
          <div className="flex items-start gap-2">
            <ShieldX className="w-4 h-4 text-red-600 shrink-0 mt-0.5" />
            <div>
              <p className="font-semibold text-red-700">Defective</p>
              <p className="text-slate-400">Operator confirms blade must be discarded.</p>
            </div>
          </div>
          <div className="flex items-start gap-2">
            <RotateCcw className="w-4 h-4 text-violet-600 shrink-0 mt-0.5" />
            <div>
              <p className="font-semibold text-violet-700">Retrain</p>
              <p className="text-slate-400">Model got it wrong — image is queued to improve the model.</p>
            </div>
          </div>
        </div>

        {/* ── Export buttons ── */}
        <div className="flex flex-wrap gap-3">
          <button
            onClick={() => generatePDF(batchResults, labels)}
            className="flex items-center gap-2 px-5 py-2.5 bg-slate-900 text-white rounded-lg text-sm font-medium hover:bg-slate-700 transition-colors"
          >
            <FileText className="w-4 h-4" />
            Export PDF Report
          </button>
          {excelReport && (
            <button
              onClick={downloadExcel}
              className="flex items-center gap-2 px-5 py-2.5 bg-emerald-600 text-white rounded-lg text-sm font-medium hover:bg-emerald-700 transition-colors"
            >
              <FileSpreadsheet className="w-4 h-4" />
              Download Excel Report
            </button>
          )}
        </div>

        {/* ── Per-image cards ── */}
        {batchResults.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-24 text-slate-400">
            <AlertTriangle className="w-10 h-10 mb-3" />
            <p className="font-medium">No results to display</p>
            <p className="text-sm mt-1">Go back and upload images to inspect</p>
          </div>
        ) : (
          batchResults.map((result, index) => {
            const isExpanded  = expandedIndex === index;
            const name        = result.filename || `Image ${index + 1}`;
            const defectCount = result.detections?.length ?? 0;
            const hasError    = !!result.error;
            const hasBodyMsg  = !!result.body_message && !hasError;
            const isDefective = !!result.blade_defective;
            const bladeLabel  = labels[index];
            const isLabeling  = !!labelLoading[index];

            // Card border colour: driven by automated result, not operator label
            const borderClass =
              hasBodyMsg  ? "border-amber-300"   :
              hasError    ? "border-slate-200"   :
              isDefective ? "border-red-300"     :
                            "border-emerald-300";

            return (
              <div
                key={index}
                className={`bg-white rounded-xl border-2 overflow-hidden transition-colors ${borderClass}`}
              >
                {/* ── Accordion header ── */}
                <button
                  className="w-full flex items-center justify-between px-6 py-4 hover:bg-slate-50 transition-colors"
                  onClick={() => setExpandedIndex(isExpanded ? null : index)}
                >
                  <div className="flex items-center gap-3 flex-wrap">
                    <span className="w-6 h-6 rounded-full bg-slate-100 text-slate-500 text-xs font-semibold flex items-center justify-center shrink-0">
                      {index + 1}
                    </span>
                    <span className="text-sm font-medium text-slate-800 truncate max-w-xs" title={name}>
                      {name}
                    </span>

                    {/* Automated result badge */}
                    {hasError ? (
                      <span className="text-xs bg-slate-100 text-slate-600 border border-slate-200 px-2 py-0.5 rounded-full">
                        Error
                      </span>
                    ) : hasBodyMsg ? (
                      <span className="text-xs bg-amber-50 text-amber-700 border border-amber-200 px-2 py-0.5 rounded-full flex items-center gap-1">
                        <ScanSearch className="w-3 h-3" /> No body found
                      </span>
                    ) : isDefective ? (
                      <span className="text-xs bg-red-50 text-red-700 border border-red-200 px-2 py-0.5 rounded-full font-semibold flex items-center gap-1">
                        <XCircle className="w-3 h-3" />
                        DEFECTIVE — {defectCount} defect{defectCount !== 1 ? "s" : ""}
                      </span>
                    ) : (
                      <span className="text-xs bg-emerald-50 text-emerald-700 border border-emerald-200 px-2 py-0.5 rounded-full font-semibold flex items-center gap-1">
                        <CheckCircle2 className="w-3 h-3" /> CLEAR
                      </span>
                    )}

                    {/* Operator label badge */}
                    {bladeLabel === "approved" && (
                      <span className="text-xs bg-emerald-100 text-emerald-800 border border-emerald-300 px-2 py-0.5 rounded-full font-semibold flex items-center gap-1">
                        <ShieldCheck className="w-3 h-3" /> Operator: Approved
                      </span>
                    )}
                    {bladeLabel === "defective" && (
                      <span className="text-xs bg-red-100 text-red-800 border border-red-300 px-2 py-0.5 rounded-full font-semibold flex items-center gap-1">
                        <ShieldX className="w-3 h-3" /> Operator: Defective
                      </span>
                    )}
                    {bladeLabel === "retrain" && (
                      <span className="text-xs bg-violet-100 text-violet-800 border border-violet-300 px-2 py-0.5 rounded-full font-semibold flex items-center gap-1">
                        <RotateCcw className="w-3 h-3" /> Retrain
                      </span>
                    )}
                  </div>

                  <div className="flex items-center gap-3 shrink-0">
                    {!hasError && !hasBodyMsg && !isDefective && <CheckCircle2 className="w-4 h-4 text-emerald-500" />}
                    {!hasError && !hasBodyMsg && isDefective   && <XCircle       className="w-4 h-4 text-red-500"     />}
                    {hasBodyMsg && !hasError                   && <ScanSearch    className="w-4 h-4 text-amber-500"   />}
                    {isExpanded
                      ? <ChevronUp   className="w-4 h-4 text-slate-400" />
                      : <ChevronDown className="w-4 h-4 text-slate-400" />}
                  </div>
                </button>

                {/* ── Accordion body ── */}
                {isExpanded && (
                  <div className="border-t border-slate-100 px-6 py-5">

                    {/* Hard error */}
                    {hasError && (
                      <div className="flex items-center gap-2 text-red-600 bg-red-50 border border-red-200 rounded-lg px-4 py-3 text-sm">
                        <AlertTriangle className="w-4 h-4 shrink-0" />
                        {result.error}
                      </div>
                    )}

                    {/* Body-server "no body" message */}
                    {hasBodyMsg && (
                      <div className="mb-5">
                        <div className="flex items-start gap-3 bg-amber-50 border border-amber-200 rounded-xl px-5 py-4">
                          <ScanSearch className="w-5 h-5 text-amber-600 shrink-0 mt-0.5" />
                          <div>
                            <p className="text-sm font-semibold text-amber-800">
                              Foreground / background separation failed
                            </p>
                            <p className="text-xs text-amber-700 mt-0.5">
                              {result.body_message}
                            </p>
                            <p className="text-xs text-amber-600 mt-2">
                              You can still label this image as <strong>Retrain</strong> below
                              so it is queued for model improvement.
                            </p>
                          </div>
                        </div>
                      </div>
                    )}

                    {/* Normal detection result */}
                    {!hasError && (
                      <div className="flex gap-6">
                        {/* Annotated image */}
                        {result.predicted_image && (
                          <div className="shrink-0">
                            <img
                              src={`data:image/png;base64,${result.predicted_image}`}
                              alt={name}
                              className="w-64 h-48 object-cover rounded-lg border border-slate-200"
                            />
                          </div>
                        )}

                        {/* Detections table or clear banner */}
                        <div className="flex-1 min-w-0">
                          {defectCount === 0 ? (
                            <div className="flex flex-col items-center justify-center h-full gap-2 text-emerald-600 bg-emerald-50 rounded-lg border border-emerald-100 py-8">
                              <CheckCircle2 className="w-8 h-8" />
                              <p className="font-semibold text-sm">No defects detected</p>
                              <p className="text-xs text-emerald-500">Blade passed automated inspection — CLEAR</p>
                            </div>
                          ) : (
                            <div>
                              {/* Defective verdict banner */}
                              <div className="flex items-center gap-2 bg-red-50 border border-red-200 rounded-lg px-4 py-2.5 mb-3">
                                <XCircle className="w-4 h-4 text-red-600 shrink-0" />
                                <p className="text-sm font-semibold text-red-700">
                                  DEFECTIVE — {defectCount} defect{defectCount !== 1 ? "s" : ""} detected
                                </p>
                              </div>

                              {/* Defect list — no ACCEPTED/REJECTED column */}
                              <div className="overflow-auto rounded-lg border border-slate-200">
                                <table className="w-full text-sm">
                                  <thead>
                                    <tr className="bg-red-700 text-white">
                                      {["DEFECT CLASS", "CONFIDENCE", "BBOX (x, y, w, h)"].map((h) => (
                                        <th key={h} className="text-left px-4 py-2.5 font-medium text-xs tracking-wide">
                                          {h}
                                        </th>
                                      ))}
                                    </tr>
                                  </thead>
                                  <tbody>
                                    {result.detections!.map((det, i) => (
                                      <tr
                                        key={i}
                                        className={`border-t border-slate-100 ${i % 2 === 0 ? "bg-white" : "bg-red-50/30"}`}
                                      >
                                        <td className="px-4 py-2.5 font-medium text-slate-800">
                                          {det.class_name}
                                        </td>
                                        <td className="px-4 py-2.5 text-center">
                                          <span className="inline-block text-xs font-semibold border rounded-full px-2.5 py-0.5 bg-slate-50 text-slate-700 border-slate-200">
                                            {(det.confidence * 100).toFixed(1)}%
                                          </span>
                                        </td>
                                        <td className="px-4 py-2.5 text-center">
                                          <code className="text-xs text-slate-500 bg-slate-100 px-2 py-0.5 rounded">
                                            {det.bbox.join(", ")}
                                          </code>
                                        </td>
                                      </tr>
                                    ))}
                                  </tbody>
                                </table>
                              </div>
                            </div>
                          )}
                        </div>
                      </div>
                    )}

                    {/* ── Operator labelling section ── */}
                    {!hasError && (
                      <div className="mt-5 pt-4 border-t border-slate-100">
                        <div className="flex items-center justify-between mb-3 flex-wrap gap-2">
                          <p className="text-xs font-semibold text-slate-500 uppercase tracking-wide">
                            Operator confirmation
                          </p>
                          <span className="text-xs text-slate-400 bg-slate-100 border border-slate-200 rounded-full px-2.5 py-0.5">
                            Optional — confirm, override, or flag for retraining
                          </span>
                        </div>

                        <div className="flex items-stretch gap-3 flex-wrap">

                          {/* APPROVED — only shown when blade is CLEAR */}
                          {!hasBodyMsg && !isDefective && (
                            <button
                              onClick={() => handleLabel(index, result, "approved")}
                              disabled={isLabeling}
                              className={`flex flex-col items-center gap-1.5 px-5 py-3 rounded-xl text-sm font-semibold border-2 transition-all disabled:opacity-60 ${
                                bladeLabel === "approved"
                                  ? "bg-emerald-600 text-white border-emerald-600 shadow-md shadow-emerald-100"
                                  : "bg-emerald-50 text-emerald-700 border-emerald-200 hover:bg-emerald-100"
                              }`}
                            >
                              {isLabeling && bladeLabel === "approved"
                                ? <Loader2 className="w-5 h-5 animate-spin" />
                                : <ShieldCheck className="w-5 h-5" />
                              }
                              <span>Approved</span>
                              <span className={`text-xs font-normal ${bladeLabel === "approved" ? "text-emerald-100" : "text-emerald-500"}`}>
                                Confirm blade is clear
                              </span>
                            </button>
                          )}

                          {/* DEFECTIVE — only shown when blade has defects (model says defective) */}
                          {!hasBodyMsg && isDefective && (
                            <button
                              onClick={() => handleLabel(index, result, "defective")}
                              disabled={isLabeling}
                              className={`flex flex-col items-center gap-1.5 px-5 py-3 rounded-xl text-sm font-semibold border-2 transition-all disabled:opacity-60 ${
                                bladeLabel === "defective"
                                  ? "bg-red-600 text-white border-red-600 shadow-md shadow-red-100"
                                  : "bg-red-50 text-red-700 border-red-200 hover:bg-red-100"
                              }`}
                            >
                              {isLabeling && bladeLabel === "defective"
                                ? <Loader2 className="w-5 h-5 animate-spin" />
                                : <ShieldX className="w-5 h-5" />
                              }
                              <span>Confirm Defective</span>
                              <span className={`text-xs font-normal ${bladeLabel === "defective" ? "text-red-100" : "text-red-400"}`}>
                                Discard this blade
                              </span>
                            </button>
                          )}

                          {/* RETRAIN — always available; shown when model is wrong */}
                          <button
                            onClick={() => handleLabel(index, result, "retrain")}
                            disabled={isLabeling}
                            className={`flex flex-col items-center gap-1.5 px-5 py-3 rounded-xl text-sm font-semibold border-2 transition-all disabled:opacity-60 ${
                              bladeLabel === "retrain"
                                ? "bg-violet-600 text-white border-violet-600 shadow-md shadow-violet-100"
                                : "bg-violet-50 text-violet-700 border-violet-200 hover:bg-violet-100"
                            }`}
                          >
                            {isLabeling && bladeLabel === "retrain"
                              ? <Loader2 className="w-5 h-5 animate-spin" />
                              : <RotateCcw className="w-5 h-5" />
                            }
                            <span>Retrain</span>
                            <span className={`text-xs font-normal ${bladeLabel === "retrain" ? "text-violet-100" : "text-violet-400"}`}>
                              {hasBodyMsg
                                ? "Image needs retraining"
                                : isDefective
                                  ? "Not actually defective"
                                  : "Defect was missed"}
                            </span>
                          </button>

                          {/* Saved confirmation */}
                          {bladeLabel && !isLabeling && (
                            <div className="flex items-center gap-2 ml-2 text-xs text-slate-400 italic self-center">
                              <CheckCircle2 className="w-3.5 h-3.5 text-emerald-500 shrink-0" />
                              Saved
                            </div>
                          )}
                        </div>

                        {labelError[index] && (
                          <p className="mt-2 text-xs text-red-500 flex items-center gap-1">
                            <AlertTriangle className="w-3.5 h-3.5" />
                            {labelError[index]}
                          </p>
                        )}

                        {bladeLabel === "retrain" && !isLabeling && (
                          <p className="mt-3 text-xs text-violet-600 bg-violet-50 border border-violet-200 rounded-lg px-3 py-2">
                            This image has been queued in the{" "}
                            <button
                              onClick={() => navigate("/retrain")}
                              className="underline font-semibold hover:text-violet-800"
                            >
                              Retrain Module
                            </button>{" "}
                            so the model can learn from this correction.
                          </p>
                        )}
                      </div>
                    )}
                  </div>
                )}
              </div>
            );
          })
        )}
      </div>
    </div>
  );
};

export default ResultsBatchPage;